public class checkForOptOut {
    /*@Future
    public static void checkIfOptedOut() {
        List<contact> contacts = [select id,opt_out_YRI__c from contact where user__c != null and isactive__c != false and opt_out_YRI__c = 'requested'];
        
        for(contact c : contacts) {
            c.opt_out_YRI__c = 'opt out';
            c.isactive__c = false;
        }
        
        update contacts;
        
    }


    */
}