public with sharing class yashOrgCConstants {
    public static final String INVALID = '.invalid';
    public static final String OPT_OUT = 'opt_out';
    public static final String REQUESTED = 'requested';
    public static final String MARKET = 'a01dL000020UisD';
    public static final String SUCCESS = 'SUCCESS';
    public static final String ERROR = 'ERROR';
    public static final String PROFILE = 'profile';
}