name: Deploy to Salesforce

on:
  push:
    branches:
      - master

  workflow_dispatch:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Salesforce CLI
        run: |
          npm install -g @salesforce/cli

      - name: Authenticate Org
        run: |
          echo "${{ secrets.SFDX_AUTH_URL }}" > auth.txt
          sf org login sfdx-url \
            --sfdx-url-file auth.txt \
            --alias targetOrg

      - name: Deploy Apex + LWC
        run: |
          sf project deploy start \
            --source-dir force-app/main/default/classes \
            --source-dir force-app/main/default/lwc \
            --source-dir force-app/main/default/triggers \
            --target-org targetOrg \
            --wait 10
