name: Deploy to Salesforce

on:
  push:
    branches:
      - master

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Salesforce CLI
        run: |
          npm install -g @salesforce/cli

      - name: Authenticate Org
        run: |
          echo "${{ secrets.SFDX_AUTH_URL }}" > auth.txt
          sf org login sfdx-url \
            --sfdx-url-file auth.txt \
            --alias targetOrg

      - name: Deploy Apex + LWC
        run: |
          sf project deploy start \
            --source-dir force-app/main/default/classes \
            --source-dir force-app/main/default/lwc \
            --target-org targetOrg \
            --wait 10
